name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    steps:
      - uses: riskledger/update-pr-description@v2
        with:
          body: |
            |            |   |
            |------------|---|
            | preview    | https://scale-visualizer.github.io/app/pr-${{ github.event.number }}/ |
            | e2e report | https://scale-visualizer.github.io/report/pr-${{ github.event.number }}/playwright-report/ |
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
          
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instal deps
        run: npm ci --prefix frontend

      - name: Build app
        run: npm run build --prefix frontend
        env:
          STATIC_PATH: '/app/pr-${{ github.event.number }}'

      - name: Deploy app preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./frontend/dist
          umbrella-dir: app

      - name: E2E
        run: |
          npm run e2e:docker

      - name: Prepare e2e report
        if: always()
        run: |
          ls
          rm -rf ./dist
          mkdir ./dist
          cp -r ./e2e/playwright-report ./dist
          cp -r ./e2e/test-results ./dist

      - name: Deploy e2e report
        if: always()
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dist
          umbrella-dir: report
